/**
 * app/robots.ts
 * Dynamic robots.txt generated by Next.js.
 * Accessible at: https://tasteofodisha1996.com/robots.txt
 */

import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/products',
          '/products/',
          '/about',
          '/contact',
          '/shipping-policy',
          '/return-policy',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/cart',
          '/checkout',
          '/payment',
          '/account',
          '/order-confirmation/',
          '/return-policy',
        ],
      },
      // Allow Google AdsBot to crawl product pages for Shopping ads
      {
        userAgent: 'Googlebot-Image',
        allow: '/TASTE OF ODISHA/',
      },
    ],
    sitemap: 'https://www.tasteofodisha1996.com/sitemap.xml',
    host: 'https://www.tasteofodisha1996.com',
  };
}
