/**
 * app/sitemap.ts
 * Dynamic sitemap generated by Next.js at build time (and on-demand for ISR).
 * Automatically includes all live product slugs from MongoDB.
 *
 * Accessible at: https://tasteofodisha1996.com/sitemap.xml
 */

import { MetadataRoute } from 'next';
import { connectDB } from '@/lib/db';

const BASE_URL = 'https://tasteofodisha1996.com';

// Static pages with their SEO priority and change frequency
const STATIC_ROUTES: MetadataRoute.Sitemap = [
  {
    url: BASE_URL,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 1.0,
  },
  {
    url: `${BASE_URL}/products`,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 0.9,
  },
  {
    url: `${BASE_URL}/products?category=sweets`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: `${BASE_URL}/products?category=muruku`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: `${BASE_URL}/products?category=achar`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  },
  {
    url: `${BASE_URL}/about`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: `${BASE_URL}/contact`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.6,
  },
  {
    url: `${BASE_URL}/shipping-policy`,
    lastModified: new Date(),
    changeFrequency: 'yearly',
    priority: 0.3,
  },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  let productRoutes: MetadataRoute.Sitemap = [];

  try {
    const { connection } = await connectDB();
    const products = await connection.db
      .collection('products')
      .find(
        { inStock: true, slug: { $exists: true, $ne: '' } },
        { projection: { slug: 1, updatedAt: 1 } }
      )
      .toArray();

    productRoutes = products.map((product) => ({
      url: `${BASE_URL}/products/${product.slug}`,
      lastModified: product.updatedAt ? new Date(product.updatedAt) : new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    }));
  } catch (err) {
    console.error('[Sitemap] Failed to fetch product slugs:', err);
  }

  return [...STATIC_ROUTES, ...productRoutes];
}
